require:
  - standard/cop/block_single_line_braces
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - rails-rspec-example/**/*
    - rails7/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 2.6

############### Style ###############

Style/FrozenStringLiteralComment:
  Enabled: true
Style/OneClassPerFile:
  Enabled: false

############### RSpec ###############

RSpec/ExampleLength:
  Enabled: false
