require:
  - standard/cop/block_single_line_braces
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - rails-rspec-example/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 2.6

############### Style ###############

Style/FrozenStringLiteralComment:
  Enabled: true

############### RSpec ###############

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - spec/factory_trace/integration_tests/empty_spec.rb
