require:
  - standard/cop/block_single_line_braces

plugins:
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - rails-rspec-example/**/*
    - rails7/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 2.7.7

############### Style ###############

Style/FrozenStringLiteralComment:
  Enabled: true

############### RSpec ###############

RSpec/ExampleLength:
  Enabled: false
