#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")
require 'factory_trace'

fail "You should pass at least one file with traced information.\nYou can generate it using only_trace mode." if ARGV.empty?

config = FactoryTrace.configuration
hash = FactoryTrace::Readers::TraceReader.read_from_files(*ARGV)
reports = FactoryTrace::Processors::FindUnused.call(hash[:defined], hash[:used])
code = reports.any? { |report| report[:code] == :unused && !report.key?(:value) } ? 1 : 0

FactoryTrace::Writers::ReportWriter.new(config.out, config).write(reports)
exit(code)
