#!/usr/bin/env ruby

$LOAD_PATH.unshift("#{__dir__}/../lib")
require 'factory_trace'

fail "You should pass at least one file with traced information.\nYou can generate it using only_trace mode." if ARGV.empty?

config = FactoryTrace.configuration
data = FactoryTrace::Readers::TraceReader.read_from_files(*ARGV)
data = FactoryTrace::Processors::FindUnused.call(data[:defined], data[:used])
code = data.size > 2 ? 1 : 0

FactoryTrace::Writers::ReportWriter.new(config.out, config).write(data)
exit(code)
